spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            provider: kakao
            client-id: "17e562df562af0446691a84a7846c65f"
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            token-grant-type: authorization_code
            authorization-response-type: code
            client-secret: vgdNT7OIaz
            scope: >
              account_email,
              birthyear,
              profile_nickname,
              name,
              age_range,
              birthday,
              phone_number
              

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token

jwt:
  secret: 236979CB6F1AD6B6A6184A31E6BE37DB3818CC36871E26235DD67DCFE4041493123432423412312312312sidjsa90dias0f9asi0d9iasd09asid09asidas9dia0s9di0as9i0
