spring:

  profiles:
    active: local

  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    username: test
    password: test

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            provider: kakao
            client-id: "17e562df562af0446691a84a7846c65f"
            token-grant-type: authorization_code
            authorization-response-type: code
            client-secret: vgdNT7OIaz
            scope: >
              account_email,
              birthyear,
              profile_nickname,
              name,
              age_range,
              birthday,
              phone_number
          naver:
            provider: naver
            client-id: 56U6XURhbeleUy6Y3Sml
            token-grant-type: authorization_code
            authorization-response-type: code
            client-secret: k1NVSjQh31
            scope: >
              id,
              nickname,
              age,
              email,
              birthday,
              birthyear
        

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me

jwt:
  secret: 236979CB6F1AD6B6A6184A31E6BE37DB3818CC36871E26235DD67DCFE4041493123432423412312312312sidjsa90dias0f9asi0d9iasd09asid09asidas9dia0s9di0as9i0

domain:
  front:
    mobile: http://localhost:3000
  backend:
    http://localhost:8080

---

spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao

          naver:
            redirect-uri: http://localhost:8080/login/oauth2/code/naver


---

spring:
  config:
    activate:
      on-profile: dev

  h2:
    console:
      enabled: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://ec2-13-125-88-75.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/kakao

          naver:
            redirect-uri: http://ec2-13-125-88-75.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/naver

